### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by bogaco** [theDreamer911/brute-force-instagram#1]
Hi @theDreamer911,

When I try to run `pip install -r requirements.txt`, I get the error message stated in the title. What can I do to fix it?

**Comment by theDreamer911** [comment]
Hi, I hope you found the solution, but let me give an advice

The requirements.txt is basically collection of python package. So, you can just install it manually

For example in this requirements.txt you will see
<ul>
<li>webbot==0.34</li>
<li>pynput==1.7.1</li>
</ul>

So you can install it manually
<ul>
<li>pip install webbot==0.34</li>
<li>pip install pynput==1.7.1</li>
</ul>

Another case, perhaps you have different pip installed in your system. 

This program runs in python3, and perhaps you can run by using pip3 install -r requirements.txt

**Comment by bogaco** [comment]
> * pip install webbot==0.34

Thank you for replying my question @theDreamer911. When I try to command `pip3 install -r requirements.txt`, I get the following error:

Building wheel for evdev (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6y5mpvj5/evdev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6y5mpvj5/evdev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bh1l7dux
       cwd: /tmp/pip-install-6y5mpvj5/evdev/
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/evdev
  copying evdev/util.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/ecodes.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/__init__.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/device.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/uinput.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/genecodes.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/ff.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/eventio_async.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/evtest.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/eventio.py -> build/lib.linux-x86_64-3.9/evdev
  copying evdev/events.py -> build/lib.linux-x86_64-3.9/evdev
  running build_ext
  running build_ecodes
  writing ecodes.c (using /usr/include/linux/input.h /usr/include/linux/input-event-codes.h /usr/include/linux/uinput.h)
  building 'evdev._input' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/evdev
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-euU3fN/python3.9-3.9.1=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-euU3fN/python3.9-3.9.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c evdev/input.c -o build/temp.linux-x86_64-3.9/evdev/input.o -std=c99 -Wno-error=declaration-after-statement
  evdev/input.c:10:10: fatal error: Python.h: No such file or directory
     10 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for evdev
  Running setup.py clean for evdev
Failed to build evdev
Installing collected packages: evdev, pynput
    Running setup.py install for evdev ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6y5mpvj5/evdev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6y5mpvj5/evdev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j5uj2m_q/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/evdev
         cwd: /tmp/pip-install-6y5mpvj5/evdev/
    Complete output (28 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/evdev
    copying evdev/util.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/ecodes.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/__init__.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/device.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/uinput.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/genecodes.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/ff.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/eventio_async.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/evtest.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/eventio.py -> build/lib.linux-x86_64-3.9/evdev
    copying evdev/events.py -> build/lib.linux-x86_64-3.9/evdev
    running build_ext
    ecodes.c already exists ... skipping build_ecodes
    building 'evdev._input' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/evdev
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-euU3fN/python3.9-3.9.1=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-euU3fN/python3.9-3.9.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c evdev/input.c -o build/temp.linux-x86_64-3.9/evdev/input.o -std=c99 -Wno-error=declaration-after-statement
    evdev/input.c:10:10: fatal error: Python.h: No such file or directory
       10 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
    ----------------------------------------

Do you know how I can deal with it?

**Comment by theDreamer911** [comment]
I think your problem, is nearly the same with this

[https://github.com/scrapy/scrapy/issues/2115
](https://github.com/scrapy/scrapy/issues/2115
)
