### ISSUE TITLE
Traceback (most recent call last):  Issue

### ISSUE THREAD

**Issue by Sanjivshen** [theDreamer911/brute-force-instagram#2]
Choose Dictionary: Dictionary
Traceback (most recent call last):
  File "/home/sanjivshen/Downloads/brute-force-instagram-main/instagram-brute-force.py", line 7, in <module>
    file = open(f'{dictionary}.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'Dictionary.txt'

**Comment by sahil-dhuri** [comment]
dont put file extension....as a input type only name of file for eg "dictionary"
@Sanjivshen

**Comment by sahil-dhuri** [comment]
> 
> 
> Choose Dictionary: Dictionary
> Traceback (most recent call last):
> File "/home/sanjivshen/Downloads/brute-force-instagram-main/instagram-brute-force.py", line 7, in
> file = open(f'{dictionary}.txt', 'r')
> FileNotFoundError: [Errno 2] No such file or directory: 'Dictionary.txt'

dont put file extension....as a input type only name of file for eg "dictionary"

**Comment by theDreamer911** [comment]
@Sanjivshen @sahil-dhuri well you write 'Dictionary' with title case, it should be lowercase 'dictionary'

Actually you can read the last line to fine what is the error
