### ISSUE TITLE
it crashes as soon as I run the "Choose Dictionary: dictionary"

### ISSUE THREAD

**Issue by ApplicationList** [theDreamer911/brute-force-instagram#9]
I've created a test account and wrote in the dictionary.txt the password to test this but it just crashes.

**Comment by theDreamer911** [comment]
Which one is crashed?

I forget big thing to said, that the program actually ask you to input the title of dictionary only (without txt), you can change it with whatever you want

![image](https://user-images.githubusercontent.com/71202864/128652376-b0ccb494-5a07-4126-a6ec-92b2f09d41ee.png)
